### ISSUE TITLE
Component not showing up

### ISSUE THREAD

**Issue by bennett-sh** [lightning-joyce/chromeai#4]
I've followed all steps in the guide however on chrome://components, the required component is not shown. I've already set my primary language to english like mentioned in some guides but it doesn't show up nontheless.
![image](https://github.com/lightning-joyce/chromeai/assets/110846042/73af1600-03c5-4d2f-bca9-082f32ed8005)
![chrome___components_](https://github.com/lightning-joyce/chromeai/assets/110846042/c4cbdf41-d3eb-4cdd-b2dd-f50c3af7d3fa)

**Comment by emmachase** [comment]
You can check `chrome://histograms/` to see the `OptimizationGuide.ModelExecution.OnDeviceModelInstallCriteria.AtRegistration` to determine why you are unable to install it. Most likely you are missing `AtRegistration.FeatureUse` (although `AtRegistration.DiskSpace` is probably common as well). To get FeatureUse, you need to have used one of chrome's other built-in AI features recently; like their AI wallpaper feature or Text Compose assistant. Try using those and then restarting your browser.

**Comment by VineshReddy** [comment]
Click check for update on all the options from start to end, this somehow worked and showed optimization-guide-on-device-model.

and restart

**Comment by bennett-sh** [comment]
That didn't work sadly.

**Comment by bennett-sh** [comment]
Also, I'm not quite sure how to read this, however here is my chrome://histograms.
![image](https://github.com/lightning-joyce/chromeai/assets/110846042/aadd86b3-2dd2-41bd-81e8-21d075b729aa)
One thought I had was that it's because I'm in Germany, however German articles mention that the steps I took are enough and I even tried setting my Google Account region & my VPN to the US.

**Comment by emmachase** [comment]
Your DiskSpace and FeatureUse metrics have a mean=0.0 which means you didn't meet the requirements. Free up at least 20GB of disk space and use some chrome AI features (try right clicking into a textbox and choose the "help me write" option, you may need to turn on generative AI features in your chrome settings first).

**Comment by matijagrcic** [comment]
[Get started with Help me write in Chrome](https://support.google.com/chrome/answer/14582048?hl=en)


To use this feature, make sure that you:

- Are located in the US and at least 18 years old
- Have English as the language of your Chrome browser. [Learn how to change Chrome languages](https://support.google.com/chrome/answer/173424)

`chrome://settings/languages`
- Are signed in to your Google Account
- Turn on [Make searches and browsing better](https://support.google.com/chrome/answer/13844634#make_searches_and_browsing_better&zippy=%2Cyoure-in-control)

`chrome://settings/syncSetup?search=Make+searches+and+browsing+better`
>Sends URLs of pages you visit to Google

This feature is only available in English, and on Windows, Mac, and Linux at this time.

**Comment by lightning-joyce** [comment]
I did a test with a new machine.

After I completed steps 1, 2 and 3, I restarted the browser.
I did not see "Optimization Guide On Device Model" in "chrome://components/".

So I set the options in steps 2 and 3 to "false". Then **restarted the browser**.
After that, re-execute steps 2 and 3. **Restart the browser**. Wait for 3 minutes after startup. Then **restart the browser again**.
Then I can see "Optimization Guide On Device Model" in "chrome://components/".

I'm not logged into my Google account and I haven't changed the language of the settings. (The default is English, not US).
Please let me know if anyone has had success with this.

**Comment by bennett-sh** [comment]
Yeah so the component still doesn't show up, however `window.ai.createTextSession` now works. I reset my settings, signed out of Chrome Dev & restarted it (though I think signing out was the key). Also again I'm not in the US, didn't change my region, haven't used Help me write etc. (it's not available for me) and from a friend I've seen that you don't even have to change your language or enable the improve search suggestions option.

**Comment by zoubingwu** [comment]
but how can you download the model? the `await window.ai.canCreateTextSession()` still returns `after-download`

**Comment by zoubingwu** [comment]
Weird, I too tried signing out and restarting the browser a couple of times, but I couldn't see the option. A couple of minutes later when I was about to give up, the Optimization Guide On Device Model options suddenly showed up!
